DROP TABLE IF EXISTS payments;

CREATE TABLE payments
(
    id  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    pmt_no VARCHAR(32) UNIQUE NOT NULL,
    pmt_amt  NUMERIC(12,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);