management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    defaults:
      enabled: false

spring:
  application:
    name: legendary-integration
  mail:
    host: smtp.qq.com
    port: 465
    username: mjd507@qq.com
    password: ${mail_authorization_code}
    protocol: smtps
    ssl:
      enabled: true
    properties:
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 3000
      "[mail.smtp.writetimeout]": 5000
  data:
    redis:
      host: localhost
      port: 6379
      client-type: lettuce
  activemq:
    broker-url: vm://localhost?broker.persistent=false
  integration:
    annotations.enable: false

mail:
  host: imap.qq.com
  port: 993
  username: mjd507@qq.com
  password: ${mail_authorization_code}
  protocol: imaps

file:
  writing-dir: ${java.io.tmpdir}/random-folder/
  reading-dir: ${java.io.tmpdir}/random-folder/

sftp:
  host: localhost
  port: 22
  user: jiandong
  password: ${sftp_password}
  dirs:
    meta_data_dir: ${java.io.tmpdir}/Meta_Data
    remote_dir: ${java.io.tmpdir}/SFTP_Remote
    local_dir: ${java.io.tmpdir}/SFTP_Local
